# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-06-08 14:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('artykul', '0002_auto_20160608_1637'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kategoria',
            name='owner',
        ),
    ]
