# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-06-08 14:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('artykul', '0003_remove_kategoria_owner'),
    ]

    operations = [
        migrations.RenameField(
            model_name='kategoria',
            old_name='description',
            new_name='opis',
        ),
    ]
