# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-06-10 08:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artykul', '0006_auto_20160609_0808'),
    ]

    operations = [
        migrations.RenameField(
            model_name='artykul',
            old_name='content',
            new_name='zawartosc',
        ),
        migrations.AlterField(
            model_name='artykul',
            name='teaser',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
